/**
 * server.mjs — TestTown mock authorities HTTP server (zero dependencies).
 *
 * Serves the TestTown registry JSON files over HTTP so the admission
 * gate can cross-check issuer claims against "the IRS" and "the
 * Secretary of State" over the network — exactly as it will someday
 * cross-check against real government APIs.
 *
 * ENDPOINTS (all GET, all read-only):
 *   GET /irs/ein/:ein
 *     200 { legalName, status, revokedReason? }   — EIN exists
 *     404 { error: "EIN not found" }              — EIN never issued
 *
 *   GET /state/registration/:id
 *     200 { legalName, standing, officers? }      — filing exists
 *     404 { error: "registration not found" }     — no such filing
 *
 *   GET /state/accreditors
 *     200 { accreditors_of_record: string[] }     — all recognized accreditors
 *
 *   GET /health
 *     200 { status: "ok", registries: "loaded" }  — liveness probe
 *
 * USAGE:
 *   node registries/server/server.mjs              # default port 9876
 *   node registries/server/server.mjs --port 8080  # custom port
 *
 * The server loads both registry JSON files ONCE at startup (they are
 * generated by tools/generate_population.py and do not change at
 * runtime). Each request is a simple in-memory lookup — no file I/O
 * per request, no database, no external calls.
 *
 * John's learning note: `process.argv` is the list of command-line
 * arguments. The first two are always ["node", "/path/to/script.mjs"],
 * so we slice from index 2 to get just OUR arguments. The `--port` flag
 * is parsed by looking for it in the array and taking the next value.
 */

import { createServer } from 'node:http';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// __dirname tells us "what folder is this script in?" — essential for
// finding the registry JSON files relative to the script's location,
// no matter what directory you run the command from.
const __dirname = dirname(fileURLToPath(import.meta.url));
const REGISTRIES_DIR = join(__dirname, '..');

// ---- Parse command-line args (e.g. --port 8080) ----
const portArg = process.argv.indexOf('--port');
const PORT = portArg !== -1 && process.argv[portArg + 1]
  ? parseInt(process.argv[portArg + 1], 10)
  : 9876; // default port — chosen to avoid common dev ports (3000, 8080, etc.)

// ---- Load registries ONCE at startup ----
// readFileSync reads the entire file into memory as a string, then
// JSON.parse turns that string into a JavaScript object. We do this
// once (not per request) because the files are small and never change
// while the server runs.
const irsData = JSON.parse(
  readFileSync(join(REGISTRIES_DIR, 'irs-ein-registry.json'), 'utf8'),
);
const stateData = JSON.parse(
  readFileSync(join(REGISTRIES_DIR, 'state-corporations-registry.json'), 'utf8'),
);

// ---- Helper: send a JSON response ----
// res is the response object Node gives us. We set the status code,
// write a JSON string as the body, and end the response. The
// Content-Type header tells the client "this is JSON, not HTML."
function sendJson(res, statusCode, body) {
  const json = JSON.stringify(body);
  res.writeHead(statusCode, {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*', // CORS: allow any origin (test server only)
  });
  res.end(json);
}

// ---- Helper: send a 404 ----
function send404(res, message) {
  sendJson(res, 404, { error: message });
}

// ---- Create the HTTP server ----
// createServer takes a callback that runs for EVERY incoming request.
// req is the request (method, URL, headers); res is what we write back.
const server = createServer((req, res) => {
  // Parse the URL: new URL() splits it into pathname + search params.
  // We use `http://localhost` as a fake base so URL() can parse a
  // path-only string like "/irs/ein/82-4410973".
  const url = new URL(req.url, `http://localhost`);

  // ---- Route: GET /health ----
  if (url.pathname === '/health') {
    sendJson(res, 200, { status: 'ok', registries: 'loaded' });
    return;
  }

  // ---- Route: GET /state/accreditors ----
  if (url.pathname === '/state/accreditors') {
    sendJson(res, 200, { accreditors_of_record: stateData.accreditors_of_record ?? [] });
    return;
  }

  // ---- Route: GET /irs/ein/:ein ----
  // pathname.split('/') turns "/irs/ein/82-4410973" into
  // ["", "irs", "ein", "82-4410973"]. We check the first 3 segments
  // and take the 4th as the EIN. decodeURIComponent handles any
  // URL-encoded characters (though EINs are just digits and dashes).
  const irsMatch = url.pathname.match(/^\/irs\/ein\/(.+)$/);
  if (irsMatch) {
    const ein = decodeURIComponent(irsMatch[1]);
    const entry = irsData.eins[ein];
    if (!entry) {
      send404(res, `EIN ${ein} not found in IRS registry`);
    } else {
      // Return only the fields the gate needs (legalName, status,
      // revokedReason) — not the "issued" date or other metadata.
      sendJson(res, 200, {
        legalName: entry.legalName,
        status: entry.status,
        ...(entry.revokedReason ? { revokedReason: entry.revokedReason } : {}),
      });
    }
    return;
  }

  // ---- Route: GET /state/registration/:id ----
  const regMatch = url.pathname.match(/^\/state\/registration\/(.+)$/);
  if (regMatch) {
    const regId = decodeURIComponent(regMatch[1]);
    const entry = stateData.registrations[regId];
    if (!entry) {
      send404(res, `registration ${regId} not found in State registry`);
    } else {
      // Return only the fields the gate needs.
      sendJson(res, 200, {
        legalName: entry.legalName,
        standing: entry.standing,
        ...(entry.officers ? { officers: entry.officers } : {}),
      });
    }
    return;
  }

  // ---- No route matched ----
  send404(res, `unknown path: ${url.pathname}`);
});

// ---- Start listening ----
// server.listen(port) tells the OS "I want to receive connections on
// this port." The callback runs once when the server is ready.
server.listen(PORT, () => {
  console.log(`TestTown registries server listening on http://localhost:${PORT}`);
  console.log(`  GET /irs/ein/:ein           — IRS EIN lookup`);
  console.log(`  GET /state/registration/:id — State registration lookup`);
  console.log(`  GET /state/accreditors      — list recognized accreditors`);
  console.log(`  GET /health                 — liveness probe`);
  console.log(`  ${Object.keys(irsData.eins).length} EINs, ${Object.keys(stateData.registrations).length} registrations loaded`);
});
